# Generated by Django 3.2 on 2021-04-27 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('adres', models.CharField(max_length=50)),
                ('completed_projects', models.IntegerField()),
                ('perspectief_clients', models.IntegerField()),
                ('happy_clients', models.IntegerField()),
                ('about_me', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=13)),
                ('message', models.TextField()),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('website_link', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('eCommerce / Django', 'eCommerce Django'), ('Portfolio', 'Portfolio'), ('Website', 'Website'), ('LogoDesign', 'LogoDesign'), ('WebDesign', 'WebDesign')], max_length=255)),
                ('upload_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=146)),
                ('upload_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesLogos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('company_logo', models.ImageField(upload_to='')),
                ('website_link', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(max_length=146)),
                ('person_name', models.CharField(max_length=50)),
                ('person_function', models.CharField(max_length=50)),
                ('person_Profile', models.ImageField(default='/hello.png/', upload_to='')),
                ('upload_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
